import imageList from "../images/imageList"
const slides = [
    { index: 0,
      id: 'turdBurgler',
      background: 'green',
      className: 'greenbck',
      img: imageList.turdBurgler, 
      price: '$5.00',
      title: 'Turd Burgler',
      category: 'stranger',
      calories: '789 calories',
      description: 'Two chocolate cake donuts smothered in cookie butter glaze. Oreo chocolate chip cookie dough. With fudge drizzle.'
    },
    { index: 1,
        id: 'rainbowPony',
        background: 'pink',
        className: 'pinkbck',
        img: imageList.rainbow, 
        price: '$1.25',
        title: 'Rainbow Pony',
        category: 'classic',
        calories: '419 calories',
        description: 'Sprinkles. Blue frosting. What else do you need?'
      },
      { index: 2,
        id: 'glazedDone',
        background: 'red',
        className: 'redbck',
        img: imageList.glazed, 
        price: '$1.25',
        title: 'Glazed Donut',
        category: 'classic',
        calories: '350 calories',
        description: 'Just a glazed done.'
      },
      { index: 3,
        id: 'vanillaFat',
        background: 'green',
        className: 'greenbck',
        img: imageList.vFatSteve, 
        price: '$1.25',
        title: 'Vanilla Fat Steve',
        category: 'classic',
        calories: '375 calories',
        description: 'Long John’s long forgotten cousin, Fat Steve.'
      },
      { index: 4,
        id: 'chocolateFat',
        background: 'blue',
        className: 'bluebck',
        img: imageList.cFatSteve, 
        price: '$1.25',
        title: 'Chocolate Fat Steve',
        category: 'classic',
        calories: '375 calories',
        description: 'Long John’s long forgotten cousin, Fat Steve.'
      },
      { index: 5,
        id: 'PBJ',
        background: 'blue',
        className: 'bluebck',
        img: imageList.pbj, 
        price: '$2.25',
        title: 'PBJ (Grape)',
        category: 'creation',
        calories: '450 calories',
        description: 'Start your day with a little bit of Peanut Butter Jelly Time.'
      },
      { index: 6,
        id: 'frenchToast',
        background: 'green',
        className:'greenbck',
        img: imageList.frenchToast, 
        price: '$2.25',
        title: 'French Toast',
        category: 'creation',
        calories: '325 calories',
        description: 'Delight yourself with a little bit of French Toast.'
      },
      {
        index: 7, 
        id: 'cookieMonster',
        background: 'pink',
        className: 'pinkbck',
        img: imageList.cookeMonster,
        price: '$2.25',
        title: 'Cookie Monster',
        category: 'creation',
        calories: '400 calories',
        description: 'It’ll make you say, “Oh nom nom nom nom nom.” '
      },
      {
        index: 8,
        id: 'Gooey Butter',
        background: 'blue',
        className: 'bluebck',
        img: imageList.gooeyButter,
        price: '$2.25',
        title: 'Gooey Butter',
        category: 'creation',
        calories: '450 calories',
        description: 'Can’t stay in St. Louis without this classic treat.'
      },
      {
        index: 9,
        background: 'red',
        id: 'mapleBacon',
        className: 'redbck',
        img: imageList.bacon,
        price: '$2.25',
        title: 'Maple Bacon',
        category: 'creation',
        calories: '425 calories',
        description: 'Because bacon is life. '
      },
      {
        index: 10,
        id: 'dingDong',
        background: 'blue',
        className: 'bluebck',
        img: imageList.dingDong,
        price: '$2.25',
        title: 'Ding Dong',
        category: 'creation',
        calories: '415 calories',
        description: 'Indulge your inner child and grab an adult sized Ding Dong. '
      },
      {
        index: 11,
        id: 'bartsRevenge',
        background: 'green',
        className: 'greenbck',
        img: imageList.bartsRevenge,
        price: '$2.25',
        title: "Bart's Revenge",
        category: 'creation',
        calories: '390 calories',
        description: 'Chocolate donut sprinkled with Butterfingers. Bart would be proud. '
      },
      {
        index: 12,
        id: 'magic',
        background: 'pink',
        className: 'pinkbck',
        img: imageList.mcr,
        price: '$2.25',
        title: "Majestic Unicorn Cinnamon Roll",
        category: 'creation',
        calories: '425 calories',
        description: 'Unicorns are paid tribute in this classic cinnamon roll sprinkled with fruity pebbles. '
      },
      {
        index: 13,
        id: 'cocoaPeblets',
        background: 'blue',
        className: 'bluebck',
        img: imageList.cocoaP,
        price: '$2.25',
        title: "Cocoa Peblits",
        category: 'creation',
        calories: '390 calories',
        description: 'Cocoa pebbles aren’t just a cereal treat.'
      },
      {
        index: 14,
        id: 'handpie',
        background: 'red',
        className: 'redbck',
        img: imageList.handpie,
        price: '$3.00',
        title: "Apple Pie",
        category: 'handpie',
        calories: '270 calories',
        description: 'You’re the apple of my eye, my little handpie.'
      },
      {
        index: 15,
        id: 'cinnabon',
        background: 'green',
        className: 'greenbck',
        img: imageList.cinnamonRoll,
        price: '$3.00',
        title: "Cinnamon Roll",
        category: 'roll',
        calories: '210 calories',
        description: 'Classic cinnamon. It’s beautiful and simple.'
      },
      {
        index: 16,
        id: 'chocolateChip',
        background: 'blue',
        className: 'bluebck',
        img: imageList.cookie,
        price: '$1.50',
        title: "Chocolate Chip",
        category: 'dookie',
        calories: '210 calories',
        description: 'Chocolate Chip. There’s nothing else greater.'
      },
      {
        index: 17,
        id: 'dripCoffee',
        background: 'green',
        className: 'greenbck',
        img: imageList.dripCoffee,
        price: '$3.00',
        title: "Drip Coffee",
        category: 'coffee',
        calories: '10 calories',
      },      
      {
        index: 18,
        id: 'latte',
        background: 'blue',
        className: 'bluebck',
        img: imageList.latte,
        price: '$4.00',
        title: "Latte",
        category: 'coffee',
        calories: '125 calories',
      },
      {
        index: 19,
        id: 'nitroBrew',
        background: 'blue',
        className: 'bluebck',
        img: imageList.nitro,
        price: '$4.00',
        title: "Nitrobrew",
        category: 'coffee',
        calories: '10 calories',
      },
      {
        index: 20,
        id: 'shots',
        background: 'pink',
        className: 'pinkbck',
        price: '$4.00',
        title: "Shots",
        category: 'coffee',
        calories: '10 calories',
      },
      {
        index: 21,
        id: 'twoPercent',
        background: 'blue',
        className: 'bluebck',
        img: imageList.regularMilk,
        price: '$2.00',
        title: "2% Milk",
        category: 'milk',
        calories: '120 calories',
        description: 'Milk from a local dairy farm, Rolling Fields.'
      },
      {
        index: 22,
        id: 'strawberryMilk',
        background: 'pink',
        className: 'pinkbck',
        img: imageList.straw,
        price: '$2.00',
        title: "Strawberry Milk",
        category: 'milk',
        calories: '180 calories',
        description: 'Milk from a local dairy farm, Rolling Fields.'
      },
      {
        index: 23,
        id: 'chocolateMilk',
        background: 'green',
        className: 'greenbck',
        img: imageList.coldCocoa,
        price: '$2.00',
        title: "Chocolate Milk",
        category: 'milk',
        calories: '180 calories',
        description: 'Milk from a local dairy farm, Rolling Fields.'
      },

]; 
export default slides;